#!/bin/bash
#usage: ls | xargs -I '{}' git-st-one '{}'

DEFAULT_STAT="# On branch master nothing to commit (working directory clean)"

cd $(pwd)/$1
git_status=$(git status)
if [ "$(echo $git_status)" != "$DEFAULT_STAT" ]; then
  echo -e "$1\n$git_status"
fi
