#!/bin/bash

DEFAULT_STAT="# On branch master nothing to commit (working directory clean)"

for p in $(ls); do
  cd $p
  git_status=$(git status)
  if [ "$(echo $git_status)" != "$DEFAULT_STAT" ]; then
    echo -e "$p\n$git_status"
  fi
  cd ..
done
